export const wonderful_image = [
    "                                                              ",
    "                         +++x+xxxXXXXXXX+ xx                  ",
    "                   x    xxXXXX$$$$$$$$$XxX$Xx                 ",
    "                 xXX$$XXxx$$$$$$$&&&$$$$$$$$Xx++              ",
    "              xXXX$$$$$$$$$$$$$$&&&&&&$X$$&&$XXXx             ",
    "               +xxXXXXXX$$$$$&&$&&&&&&XX$$$$$X$$XxX++         ",
    "             +xXXXXXXXX$$$$$&&&$&&&&&$X$$$$$$$$$$$$$Xx+       ",
    "          +xxxXX$$X$XX$$$$$$&&&$&&&&$$$$$$$$$$X$$$$$$$$X+     ",
    "          +XXX$$$$$$$$$$$$$$$$$$XXXXX$$$$$$$&$$$$$$$$$$Xx     ",
    "         +XXX$$$$$$$XXXxxxx++++++++++xxXXX$$$$$$$$$$$X$$$Xx   ",
    "        +xXX$$$$$$$Xxx++++++++++++;;;;+++++xxXX$$$$$$$$$&$X   ",
    "        +XX$$&&&$$Xxx++++++++++++;;;;;+++++++xxxX$$$$$$$$$$x  ",
    "        +X$$&&&&$Xx++++++++;;;;;;;;;;;;;++++++xxxxX$$$$$$X$X+ ",
    "         x$&&&&$$X+++++++++;;;;;;;;;;;;;;++++++++xxX$$$$$$$$x ",
    "         x$$&$$$$x+++++++++;;;;;;;;;;;;;;;++++++++xX$$$$$$$$X ",
    "         x$$$$$$Xx+++++++;;;;;;;;;;;;;;;;;++++++++xX$&$$$$$$X ",
    "         x$$$$$$xx++++++;;;;;;;;;;;;;;;;;;++++++++xX$$&$$$$$X ",
    "          X$$&$Xxx++++++;;;;;:::;;;;;;;;;;;;++++++xX$$$$$$$$x ",
    "          X$$$$xx++xxxxxx+;;::::::::::::;;;++++++xxX$$$$$$$x  ",
    "         +X$$$Xx+xXXXxxXXXXx+;;;:::;::;;+xxxxxx++xxX$$$$X$Xx  ",
    "         x$$$$X+xXx+++++++xxx++;;;;;;+xXX$XXXX$XXxxx$$$$$$X   ",
    "        ++X$$$x++++xXXXxxXxxxx++;;;+++xx+++;+++x$XxxX$$$$$X   ",
    "       +xxx$$X+++xxXXXX$$+;xxxx+;;+++xxxxx+xxxx++XXxX$$$$$x   ",
    "       +x++X$x++;;+++++;;+++++x++++xx++x+xXXX$$Xx++xX$$$$$x   ",
    "       ++;;XX+++++++++++++;+++x++;+xx+++++;++++++++xX$$$$Xx;  ",
    "       +;;;x++++++;;;;;;;;;;+xx++;+x++++;;;;;+;;;+xxx$$X+x+;  ",
    "       ;;++++++++++;;;;:;;;++++;::;+xx+;;;;;;;;;;++xxXX+:++;  ",
    "       ;+x++x++++++;;;;++;+xxxx+;;+x+++;;;::;;;;+++xxXx;:;;:  ",
    "       +++;+xxx++++;;;++++xXXXxxxxxxxxx+;+;;;;;;+++xxX++;:;:  ",
    "        +;;+xxxx+++;;;;+xxxxxxx+++xXXxxxx+++;;;+++xxXX+;;;;   ",
    "         +xxxxxx+++;;+++++++x+++;++++xxxxx++++++++xxXx++;+;   ",
    "            +xxxx++;;+++xXx;++;:;;;+++xxx++++;++++xXX+;+++    ",
    "            +xxxx+++;+;+X++:::..:.::;:+xXx+++;+++xxXx++++     ",
    "             xxxxxx++++;+xx+;:::::::;;+xx++++++++xXX+ ;       ",
    "             xXxxxxxxx+;+xxxx++;;;++xxx+++xx++++xxXx          ",
    "             +xXxxxxXXx++++++++++++++++++xXx++++xXX+          ",
    "              +XXXXxXXXx++++++++++++++++xXXx++xxXXx           ",
    "               x$$XXX$XXxx+++++;;++++++xXXXXxXX$Xx            ",
    "               +x$$$XXXXXxxx++;;;;+++xxXXXXXX$$$x             ",
    "         ;+xXXXxxXX$$$$XXXxx+;;;;;++xxXXX$$$$$Xx+             ",
    "      +XX$$&&&XxxxxXX$$$XXXxx++++++xxxX$$$$$Xxxx+             ",
    "     x$$&&&&&&XxxxxxXXX$$$$XXXXxXXXXX$$$$XXXxxx$$Xx           ",
    "   xX$&$&&&&&$xxx++xxxXXxxX$$$$$$$$$$XXXXXxxxxx$&&$xx         ",
    "  x$$$$&&&&&$x+x+++++xxXxx+xxxxxxxxxxxxxxxxxxxX&&&&&$x        ",
    " X$$$$&&&&&&x+x+++++++xxxx++++++++++xxxxxxxxxxX&&&&&&$X       ",
    "X$$$$&&&&&&X++x+++++++xxxx++++++++++xxxxx+++xxX$&&&&&&$       ",
    "$$$$&&&&$X$x+++++++++++xx+++++++++++xxx+++++xxXX&&&&&&&X      ",
    "============================================================= ",
    "         Cyber Andrew Will Bless Your Application!            ",
    "============================================================= ",
];